name: build-android-apk

on:
  workflow_dispatch: {}   # lo ejecutas a mano desde Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Buildozer ya preinstalado (SDK/NDK incluidos)
      - name: Build with Buildozer
        uses: kivy/buildozer-action@master
        with:
          command: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: bin/*.apk
